server:
  port: 8083

spring:
  application:
    name: APPOINTMENT-SERVICE
  datasource:
    url: jdbc:h2:mem:appointmentdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    management:
      endpoints:
        web:
          exposure:
            include: "*"
      tracing:
        sampling:
          probability: 1.0


      zipkin:
        base-url: http://localhost:9411
      sleuth:
        sampler:
          probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
