server:
  port: 8082

spring:
  application:
    name: DOCTOR-SERVICE

  datasource:
    url: jdbc:h2:mem:doctordb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always

logging:
  level:
    io.micrometer.tracing: DEBUG
    org.springframework.web: DEBUG
    io.zipkin.reporter: DEBUG



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

