server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
              - Path=/api/patients/**
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always 

logging:
  level:
    io.micrometer.tracing: DEBUG
    org.springframework.web: DEBUG
    io.zipkin.reporter: DEBUG



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
