server:
  port: 8081

spring:
  application:
    name: PATIENT-SERVICE

  datasource:
    url: jdbc:h2:mem:patientdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

  zipkin:
    base-url: http://localhost:9411  # Ensure it is reachable
    enabled: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # Ensure 100% of requests are traced
  endpoints:
    web:
      exposure:
        include: "*"  # Enable Actuator endpoints
  health:
    show-details: always
    mappings:
      enabled: true
    info:
      enabled: true

logging:
  level:
    io.opentelemetry: DEBUG
    org.springframework.web: DEBUG
    io.zipkin.reporter: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
