server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

spring:
  application:
    name: EUREKA-SERVER
  cloud:
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: always
  security:
    enabled: false

logging:
  level:
    io.micrometer.tracing: DEBUG
    org.springframework.web: DEBUG
    io.zipkin.reporter: DEBUG

